/// Flutter icons TipyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TipyIcons
///      fonts:
///       - asset: fonts/TipyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TipyIcons {
  TipyIcons._();

  static const _kFontFam = 'TipyIcons';
  static const _kFontPkg = null;

  static const IconData globe = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crescent_moon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble_3 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gong = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_4 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_6 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clacket = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
